#!/bin/bash
# ─────────────────────────────────────────────────────────────
# Talk to my files
# Double-click to chat with the AI about the files in this
# folder. No coding knowledge needed.
# (Generated by the agent-friendly-knowledge-docs skill.)
# ─────────────────────────────────────────────────────────────

# Enter the folder this file lives in (the "mother" folder).
cd "$(dirname "$0")" || exit 1

# Clear the screen so no scary technical text shows.
clear

# Calm colors, with a fallback if the terminal doesn't support them.
if [ -t 1 ]; then
  B=$'\033[1m'; DIM=$'\033[2m'; BLUE=$'\033[38;5;68m'; GREEN=$'\033[38;5;71m'; R=$'\033[0m'
else
  B=""; DIM=""; BLUE=""; GREEN=""; R=""
fi

printf '\n'
printf '   %s%sHi! 👋%s\n' "$B" "$BLUE" "$R"
printf '\n'
printf "   I'm the AI that knows the files in this folder.\n"
printf '   Ask me anything about them.\n'
printf '\n'
printf '   %sFor example:%s\n' "$DIM" "$R"
printf '   %s· "what'\''s in this folder?"%s\n' "$DIM" "$R"
printf '   %s· "summarize the proposal for client X"%s\n' "$DIM" "$R"
printf '   %s· "which is the latest version of the model?"%s\n' "$DIM" "$R"
printf '\n'
printf '   %s────────────────────────────────────────────%s\n' "$DIM" "$R"
printf '\n'

# Which assistants are installed?
have_claude=0; command -v claude >/dev/null 2>&1 && have_claude=1
have_codex=0;  command -v codex  >/dev/null 2>&1 && have_codex=1

status() {  # $1 = installed flag
  if [ "$1" -eq 1 ]; then
    printf '%s✓ installed%s' "$GREEN" "$R"
  else
    printf "%s— not installed, I'll help you set it up%s" "$DIM" "$R"
  fi
}

# Always show the picker, marking what's installed.
printf '   %sWhich assistant do you want to use?%s\n\n' "$B" "$R"
printf '   %s[1]%s Claude Code   ' "$B" "$R"; status "$have_claude"; printf '\n'
printf '   %s[2]%s Codex         ' "$B" "$R"; status "$have_codex";  printf '\n\n'
printf '   Type 1 or 2 and press Enter: '
read -r choice
printf '\n'

open_guide() {  # $1 = name, $2 = url
  printf "   %s isn't installed yet.%s Opening the setup guide in your browser…\n" "$B$1" "$R"
  printf '   %s%s%s\n\n' "$BLUE" "$2" "$R"
  open "$2" >/dev/null 2>&1
  printf '   First-time setup is easiest with a technical colleague. Once it'\''s\n'
  printf '   installed, just double-click here again.\n\n'
  printf '   %s(You can close this window.)%s\n\n' "$DIM" "$R"
}

case "$choice" in
  2) sel=codex ;;
  *) sel=claude ;;
esac

if [ "$sel" = codex ]; then
  if [ "$have_codex" -eq 1 ]; then codex
  else open_guide "Codex" "https://developers.openai.com/codex"; exit 0; fi
else
  if [ "$have_claude" -eq 1 ]; then claude
  else open_guide "Claude Code" "https://claude.com/claude-code"; exit 0; fi
fi

# Friendly goodbye when the conversation ends.
printf '\n   %sAll done! You can close this window. See you next time 👋%s\n\n' "$BLUE" "$R"
