#!/bin/bash
# ─────────────────────────────────────────────────────────────
# Talk to my files
# Double-click to chat with the AI about the files in this
# folder. No coding knowledge needed.
# (Generated by the agent-friendly-knowledge-docs skill.)
# ─────────────────────────────────────────────────────────────

# Enter the folder this file lives in (the "mother" folder).
cd "$(dirname "$0")" || exit 1

# Clear the screen so no scary technical text shows.
clear

# Calm colors, with a fallback if the terminal doesn't support them.
if [ -t 1 ]; then
  B=$'\033[1m'; DIM=$'\033[2m'; BLUE=$'\033[38;5;68m'; R=$'\033[0m'
else
  B=""; DIM=""; BLUE=""; R=""
fi

printf '\n'
printf '   %s%sHi! 👋%s\n' "$B" "$BLUE" "$R"
printf '\n'
printf "   I'm the AI that knows the files in this folder.\n"
printf '   Ask me anything about them.\n'
printf '\n'
printf '   %sFor example:%s\n' "$DIM" "$R"
printf '   %s· "what'\''s in this folder?"%s\n' "$DIM" "$R"
printf '   %s· "summarize the proposal for client X"%s\n' "$DIM" "$R"
printf '   %s· "which is the latest version of the model?"%s\n' "$DIM" "$R"
printf '\n'
printf '   %sJust type below and press Enter.%s\n' "$B" "$R"
printf '   %s(To leave when you'\''re done, type /exit and Enter.)%s\n' "$DIM" "$R"
printf '\n'
printf '   %s────────────────────────────────────────────%s\n' "$DIM" "$R"
printf '\n'

# Which assistants are installed?
have_claude=0; command -v claude >/dev/null 2>&1 && have_claude=1
have_codex=0;  command -v codex  >/dev/null 2>&1 && have_codex=1

run_agent() {
  case "$1" in
    codex)  codex ;;
    *)      claude ;;
  esac
}

if [ "$have_claude" -eq 1 ] && [ "$have_codex" -eq 1 ]; then
  # Both installed → let the user pick at the start.
  printf '   %sWhich assistant do you want to use?%s\n' "$B" "$R"
  printf '   %s[1]%s Claude Code    %s[2]%s Codex\n\n' "$B" "$R" "$B" "$R"
  printf '   Type 1 or 2 and press Enter: '
  read -r choice
  printf '\n'
  case "$choice" in
    2) run_agent codex ;;
    *) run_agent claude ;;
  esac
elif [ "$have_claude" -eq 1 ]; then
  run_agent claude
elif [ "$have_codex" -eq 1 ]; then
  run_agent codex
else
  # Neither found: a gentle message instead of a scary error.
  printf '   %sAlmost there!%s You just need to install an assistant once.\n' "$B" "$R"
  printf '   Ask for help installing one of these:\n'
  printf '   %s· Claude Code — https://claude.com/claude-code%s\n' "$BLUE" "$R"
  printf '   %s· Codex       — https://developers.openai.com/codex%s\n' "$BLUE" "$R"
  printf '\n   Once it'\''s installed, just double-click here again.\n\n'
  printf '   %s(You can close this window.)%s\n\n' "$DIM" "$R"
  exit 0
fi

# Friendly goodbye when the conversation ends.
printf '\n   %sAll done! You can close this window. See you next time 👋%s\n\n' "$BLUE" "$R"
