@echo off
REM ---------------------------------------------------------------
REM  Talk to my files
REM  Double-click to chat with the AI about the files in this
REM  folder. No coding knowledge needed.
REM  (Generated by the agent-friendly-knowledge-docs skill.)
REM ---------------------------------------------------------------

REM Use UTF-8 for accents and emoji (best effort on old consoles).
chcp 65001 >nul 2>nul

REM Enter the folder this file lives in (the "mother" folder).
cd /d "%~dp0"

REM Clear the screen so no scary technical text shows.
cls

echo(
echo    Hi! 👋
echo(
echo    I'm the AI that knows the files in this folder.
echo    Ask me anything about them.
echo(
echo    For example:
echo    - "what's in this folder?"
echo    - "summarize the proposal for client X"
echo    - "which is the latest version of the model?"
echo(
echo    --------------------------------------------------
echo(

REM Which assistants are installed?
set HAVE_CLAUDE=0
where claude >nul 2>nul && set HAVE_CLAUDE=1
set HAVE_CODEX=0
where codex >nul 2>nul && set HAVE_CODEX=1

set "S1=not installed - I'll help you set it up"
if "%HAVE_CLAUDE%"=="1" set "S1=installed"
set "S2=not installed - I'll help you set it up"
if "%HAVE_CODEX%"=="1" set "S2=installed"

REM Always show the picker, marking what's installed.
echo    Which assistant do you want to use?
echo(
echo    [1] Claude Code   %S1%
echo    [2] Codex         %S2%
echo(
choice /c 12 /n /m "   Type 1 or 2: "
if errorlevel 2 goto pick_codex
goto pick_claude

:pick_claude
if "%HAVE_CLAUDE%"=="1" ( claude & goto done )
where wsl >nul 2>nul && ( wsl claude & goto done )
set "GNAME=Claude Code"
set "GURL=https://claude.com/claude-code"
goto guide

:pick_codex
if "%HAVE_CODEX%"=="1" ( codex & goto done )
set "GNAME=Codex"
set "GURL=https://developers.openai.com/codex"
goto guide

:guide
echo(
echo    %GNAME% isn't installed yet. Opening the setup guide in your browser...
echo    %GURL%
start "" "%GURL%"
echo(
echo    First-time setup is easiest with a technical colleague.
echo    Once it's installed, just double-click here again.
echo(
pause
exit /b 0

:done
echo(
echo    All done! You can close this window. See you next time.
echo(
