@echo off
REM ---------------------------------------------------------------
REM  Talk to my files
REM  Double-click to chat with the AI about the files in this
REM  folder. No coding knowledge needed.
REM  (Generated by the agent-friendly-knowledge-docs skill.)
REM ---------------------------------------------------------------

REM Use UTF-8 for accents and emoji (best effort on old consoles).
chcp 65001 >nul 2>nul

REM Enter the folder this file lives in (the "mother" folder).
cd /d "%~dp0"

REM Clear the screen so no scary technical text shows.
cls

echo(
echo    Hi! 👋
echo(
echo    I'm the AI that knows the files in this folder.
echo    Ask me anything about them.
echo(
echo    For example:
echo    - "what's in this folder?"
echo    - "summarize the proposal for client X"
echo    - "which is the latest version of the model?"
echo(
echo    Just type below and press Enter.
echo    (To leave when you're done, type /exit and Enter.)
echo(
echo    --------------------------------------------------
echo(

REM Which assistants are installed?
set HAVE_CLAUDE=0
where claude >nul 2>nul && set HAVE_CLAUDE=1
set HAVE_CODEX=0
where codex >nul 2>nul && set HAVE_CODEX=1

REM Both installed -> let the user pick at the start.
if "%HAVE_CLAUDE%%HAVE_CODEX%"=="11" (
  echo    Which assistant do you want to use?
  echo(
  choice /c 12 /n /m "   [1] Claude Code   [2] Codex   -- type 1 or 2: "
  if errorlevel 2 ( codex & goto despedida )
  claude & goto despedida
)

if "%HAVE_CLAUDE%"=="1" ( claude & goto despedida )
if "%HAVE_CODEX%"=="1" ( codex & goto despedida )

REM None found natively: try Claude Code inside WSL, else a gentle message.
where wsl >nul 2>nul
if %errorlevel%==0 (
  wsl claude & goto despedida
)

echo    Almost there! You just need to install an assistant once.
echo    Ask for help installing one of these:
echo    - Claude Code - https://claude.com/claude-code
echo    - Codex       - https://developers.openai.com/codex
echo(
echo    Once it's installed, just double-click here again.
echo(
pause
exit /b 0

:despedida
echo(
echo    All done! You can close this window. See you next time 👋
echo(
